version: "3"
services:
  api:
    build: .
    command: yarn start
    volumes:
      - ./server:/usr/app/
      - ./package.json:/usr/app/package.json
      - node_modules:/usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - web
    environment:
      PORT: 4000

  web:
    build: .
    command: yarn dev
    volumes:
      - ./app:/usr/app/
      - ./package.json:/usr/app/package.json
      - node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_URL: http://localhost:4000/

volumes:
  node_modules:
